import { createElement } from 'react';
import {
  MagnifyingGlassIcon,
  DocumentTextIcon,
  PencilSquareIcon,
  ArrowPathIcon,
  CircleStackIcon,
  PlusCircleIcon,
  Bars3BottomLeftIcon,
  ChatBubbleLeftIcon,
  ChatBubbleOvalLeftEllipsisIcon,
} from '@heroicons/react/20/solid';
import type { MentionAction } from './mentionRegistry';

export const notionActions: MentionAction[] = [
  {
    id: 'notion-search',
    label: 'Search workspace',
    group: 'Notion',
    icon: createElement(MagnifyingGlassIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'search', 'find', 'workspace', 'wiki'],
    onSelect: async () => 'notion-search',
    renderer: () => 'Notion: Search',
    feedRenderer: () => '[Notion: Search workspace]',
  },
  {
    id: 'notion-read',
    label: 'Read page',
    group: 'Notion',
    icon: createElement(DocumentTextIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'read', 'fetch', 'page', 'get'],
    onSelect: async () => 'notion-read',
    renderer: () => 'Notion: Read',
    feedRenderer: () => '[Notion: Read page]',
  },
  {
    id: 'notion-create',
    label: 'Create page',
    group: 'Notion',
    icon: createElement(PencilSquareIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'create', 'new', 'page', 'add', 'write'],
    onSelect: async () => 'notion-create',
    renderer: () => 'Notion: Create',
    feedRenderer: () => '[Notion: Create page]',
  },
  {
    id: 'notion-update',
    label: 'Update page',
    group: 'Notion',
    icon: createElement(ArrowPathIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'update', 'edit', 'modify', 'page', 'change'],
    onSelect: async () => 'notion-update',
    renderer: () => 'Notion: Update',
    feedRenderer: () => '[Notion: Update page]',
  },
  {
    id: 'notion-query',
    label: 'Query databases',
    group: 'Notion',
    icon: createElement(CircleStackIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'query', 'database', 'filter', 'table'],
    onSelect: async () => 'notion-query',
    renderer: () => 'Notion: Query',
    feedRenderer: () => '[Notion: Query databases]',
  },
  {
    id: 'notion-create-database',
    label: 'Create database',
    group: 'Notion',
    icon: createElement(PlusCircleIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'create', 'database', 'new', 'table'],
    onSelect: async () => 'notion-create-database',
    renderer: () => 'Notion: Create DB',
    feedRenderer: () => '[Notion: Create database]',
  },
  {
    id: 'notion-append',
    label: 'Append blocks',
    group: 'Notion',
    icon: createElement(Bars3BottomLeftIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'append', 'blocks', 'content', 'add'],
    onSelect: async () => 'notion-append',
    renderer: () => 'Notion: Append',
    feedRenderer: () => '[Notion: Append blocks]',
  },
  {
    id: 'notion-list-comments',
    label: 'List comments',
    group: 'Notion',
    icon: createElement(ChatBubbleOvalLeftEllipsisIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'comments', 'list', 'discussion'],
    onSelect: async () => 'notion-list-comments',
    renderer: () => 'Notion: Comments',
    feedRenderer: () => '[Notion: List comments]',
  },
  {
    id: 'notion-create-comment',
    label: 'Create comment',
    group: 'Notion',
    icon: createElement(ChatBubbleLeftIcon, { width: 16, height: 16 }),
    keywords: ['notion', 'comment', 'create', 'reply', 'discuss'],
    onSelect: async () => 'notion-create-comment',
    renderer: () => 'Notion: Comment',
    feedRenderer: () => '[Notion: Create comment]',
  },
];
